### ISSUE TITLE
Non-informative stack trace

### ISSUE THREAD

**Issue by jifeon** [apsavin/bnsf#30]
When something goes wrong I get stake trace like this:

```
14:22:02.568 - error: Error process page /test-menu GET Error: Parameter "filePath" has bad value "undefined", not suitable for path generation
    at RouterBase._getParameterValue (/home/jifeon/projects/bnsf-adwiki/libs/bnsf/node_modules/router-base/lib/router-base.js:435:19)
    at /home/jifeon/projects/bnsf-adwiki/libs/bnsf/node_modules/router-base/lib/router-base.js:374:30
    at String.replace (native)
    at RouterBase._generate (/home/jifeon/projects/bnsf-adwiki/libs/bnsf/node_modules/router-base/lib/router-base.js:370:30)
    at RouterBase.generate (/home/jifeon/projects/bnsf-adwiki/libs/bnsf/node_modules/router-base/lib/router-base.js:348:29)
    at BEMContext.<anonymous> (/home/jifeon/projects/bnsf-adwiki/desktop.bundles/index/index.bemtree.js:807:35)
    at run (/home/jifeon/projects/bnsf-adwiki/desktop.bundles/index/index.bemtree.js:179:15)
    at BEMContext.<anonymous> (/home/jifeon/projects/bnsf-adwiki/desktop.bundles/index/index.bemtree.js:120:14)
    at bodyHandler (/home/jifeon/projects/bnsf-adwiki/desktop.bundles/index/index.bemtree.js:98:54)
    at apply (/home/jifeon/projects/bnsf-adwiki/desktop.bundles/index/index.bemtree.js:119:40)
```

Error message is pretty useful and complete, but stack trace is uninformative. I'm talking about:
```
/index.bemtree.js:807:35
```

It's really annoying moment during usual development

**Comment by apsavin** [comment]
It's not issue of bnsf, it's issue of bem-xjst. May be, with bem-xjst 4.x we'll get better results.

**Comment by tadatuta** [comment]
we will, source maps are comming...
